name = "Wayfarer"
author = "Tazer, Farcr"
version = "6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "246c2cd64bd1bdbdd022dd74d4eb28236fe170b58b5ecfe1014e209dd437f42e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[options]
acceptable-game-versions = ["1.21"]
