name = "Wayfarer"
author = "Tazer, Farcr"
version = "6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fce56ff16f9b518fe1644f3efac7dff92ed5c2668d793314ecc5f2859eee5096"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[options]
acceptable-game-versions = ["1.21"]
