name = "Wayfarer"
author = "Tazer, Farcr"
version = "5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "648ef99c164597c4cd3700632a25eeede045a3979f6da413e129c58f02db1942"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[options]
acceptable-game-versions = ["1.21"]
