name = "Wayfarer"
author = "Tazer, Farcr"
version = "6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bd019939d0d8452a0e51d737ad82dd91b6f31617842a078690bff1db3d85919"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[options]
acceptable-game-versions = ["1.21"]
