name = "Wayfarer"
author = "Tazer, Farcr"
version = "5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12e25421ea983ce5238e6588b124bc3cdace42af5240ba265d6ef1d4c84110fe"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"
