name = "Wayfarer"
author = "Tazer, Farcr"
version = "5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3618bd3d9476148bb18fd344fafc7db4d5c1e1eb09e711be73cb4241d4d162fb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[options]
acceptable-game-versions = ["1.21"]
