name = "Wayfarer"
author = "Tazer, Farcr"
version = "6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e6f3b2599144d1cc96066f21fe313900849306f368c3868e4d2b8d0cadce41e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[options]
acceptable-game-versions = ["1.21"]
