name = "Wayfarer"
author = "Tazer, Farcr"
version = "6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c4e30c38b34b762c25d3c41cbf0e2830f642495d0b6d5ad2af2e328fd39d6e6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"

[options]
acceptable-game-versions = ["1.21"]
