["FollowVoice Config"]
	#List of mob configurations for FollowVoice.
	#Format: 'mob_id=speed=<value>,range=<value>,threshold=<value>'
	#Example: 'minecraft:zombie=speed=1.5,range=25,threshold=-10.0'
	mob_configs = ["minecraft:zombie=speed=1.5,range=20,threshold=-40.0", "minecraft:skeleton=speed=1.2,range=15,threshold=-35.0"]
	#List of animal configurations for RunawayVoiceGoal.
	#Format: 'animal_id=speed=<value>,range=<value>,threshold=<value>'
	animal_configs = ["minecraft:cow=speed=1.5,range=15,threshold=-45.0", "minecraft:pig=speed=1.2,range=5,threshold=-45.0"]

["Whisper Config"]
	#Multiplier for detection range when the player is whispering.
	#This multiplies the range you have configured for your mobs.
	# Default: 0.5
	# Range: 0.0 ~ 1.0
	whisper_range_multiplier = 0.5
	#Multiplier for mob speed when the player is whispering.
	#This multiplies the speed you have configured for your mobs.
	# Default: 0.8
	# Range: 0.0 ~ 1.0
	whisper_speed_multiplier = 0.8

["Misc Config"]
	#Multiplier for detection range during a thunderstorm or rain.
	# Default: 0.5
	# Range: 0.0 ~ 1.0
	thunder_range_multiplier = 0.5
	#Multiplier for detection range when the player is sneaking.
	# Default: 0.5
	# Range: 0.0 ~ 1.0
	sneaking_range_multiplier = 0.5
	#List of sound reaction configurations for mobs.
	#Format: 'mob_id=speed=<value>,range=<value>,sound_types=<type1,type2,...>'
	#Example: 'minecraft:zombie=speed=1.5,range=20,sound_types=block.wood.break,block.metal.hit,modded:custom.sound'
	#How to know the sound types? Use the command /playsound <sound> <source> <player>
	sound_reaction_configs = ["minecraft:zombie=speed=1.5,range=20,sound_types=block.wood.break,block.metal.hit", "minecraft:cow=speed=1.8,range=16,sound_types=entity.cow.death,entity.cow.hurt"]
