version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = false
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEPTH"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
kubejs = true
azurelib = true
everycomp = true
farmersdelight = true
glow = true
supplementaries = true
portablehole = true
incubation = true
nomansland = true
sawmill = true
create = true
piglinproliferation = true
brewinandchewin = true
mannequins = true
clayworks = true
another_furniture = true
blockbox = true
minecraft = true
chalk = true
vanity = true
fishermens_trap = true
sootychimneys = true
snowyspirit = true
newworld = true
berry_good = true
amendments = true
goated = true
diagonalfences = true
moyai = true
wayfarer_core = true
backpacks = true
exposure = true
